project:
  type: website
  output-dir: docs
  
filters:
  - webr

website:
  title: "Beyond the \n Average Treatment Effect"
  bread-crumbs: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: instructors.qmd
        text: Instructors
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Welcome
      - href: info_tldr.qmd
        text: Introduction
      - href: info_d.qmd
        text: Defining Interventions
      - href: info_estimators.qmd
        text: Estimators
      - section: Estimation with lmtp
        contents:
          - href: lmtp.qmd
            text: The lmtp package
          - href: R_static.qmd
            text: Static effects and the ATE
          - href: R_dtr.qmd
            text: Dynamic Regimes
          - href: R_mtp.qmd
            text: Modified Treatment Policies
          - href: R_ipsi.qmd
            text: IPSI
          - href: R_survival.qmd
            text: Survival Analysis
          - href: R_multivariate.qmd
            text: Multivariate Exposures
      - href: info_conclusion.qmd
        text: Final Remarks
        
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/nt-williams/lmtp-workshop

format:
  html:
    theme: [default,styles.scss]
    css: styles.css
    toc: true
    include-in-body: macros.qmd

