project:
  type: website
  output-dir: docs
  
filters:
  - webr

website:
  title: "Beyond the \n Average Treatment Effect"
  bread-crumbs: false
  navbar:
    left:
      - href: instructors.qmd
        text: Instructors
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Welcome!
      - href: 01_info_introduction.qmd
        text: 1. Introduction
      - href: 02_info_d.qmd
        text: 2. Defining Interventions
      - href: 03_info_estimators.qmd
        text: 3. Estimators
      - section: 4. Estimating Effects with lmtp
        contents:
          - href: 04_lmtp.qmd
            text: The lmtp package
          - href: 05_R_static.qmd
            text: Static effects and the ATE
          - href: 06_R_dtr.qmd
            text: Dynamic Treatment Regimes
          - href: 07_R_mtp.qmd
            text: Modified Treatment Policies
          - href: 08_R_ipsi.qmd
            text: IPSI
          - href: 09_R_survival.qmd
            text: Survival Analysis
          - href: 10_R_multivariate.qmd
            text: Multivariate Exposures
      - href: 11_info_conclusion.qmd
        text: 5. Final Remarks
        
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/nt-williams/lmtp-workshop

format:
  html:
    theme: [default,callout_tweet.scss]
    css: styles.css
    toc: true
    include-in-body: macros.qmd

