---
title: "Instructors"
---

## [Nick Williams](https://github.com/nt-williams)

Nick is a Senior Data Analyst in Columbia University's Mailman School of Public Health, Department of Epidemiology. His interests are in the development of statistical computing tools for novel causal inference methods. He's the author and maintainer of multiple R packages. He's beginning a PhD in biostatistics Fall 2025. 

------------------------------------------------------------------------

## [Kara Rudolph](https://kararudolph.github.io/)

Kara is an Assistant Professor of Epidemiology at Columbia University, Mailman School of Public Health. Her research interests are in developing and applying causal inference methods to understand social and contextual influences on mental health, substance use, and violence. Her current work focuses on developing and applying methods for transportability and mediations to understand mechanisms relevant for drug use disorder prevention and treatment in various target populations.

------------------------------------------------------------------------

## [Iván Díaz](https://www.idiaz.xyz/)

Iván is an Associate Professor of Biostatistics at New York University Grossman School of Medicine. His research focuses on the development of non-parametric statistical methods for causal inference from observational and randomized studies with complex datasets, using machine learning. This includes but is not limited to mediation analysis, methods for continuous exposures, longitudinal data including survival analysis, and efficiency guarantees with covariate adjustment in randomized trials. He also works applying these methods to healthcare research, including in neurology, critical care, opioid use research, and other areas.
