---
title: "Incremental Propensity Score Interventions"
engine: knitr
date-modified: last-modified
filters:
  - webr
webr:
  packages: ['lmtp', 'superlearner']
  autoload-packages: true
  repos: 
    - https://nt-williams.r-universe.dev
    - https://imbs-hl.r-universe.dev
bibliography: references.bib
nocite: |
  @diaz2023nonparametric, @diaz2024causal, @kennedy2019nonparametric, @wen2023intervention
---

{{< include macros.qmd >}}

```{webr-r}
#| context: setup
download.file("https://raw.githubusercontent.com/nt-williams/lmtp-workshop/main/data/williams_synthetic.csv", "williams_synthetic.csv")
covid <- read.csv("williams_synthetic.csv")
```

Recall that an incremental propensity score intervention (IPSI) is a hypothetical intervention where the conditional probability of treatment is shifted. We defined an IPSI, based on the risk ratio, that *increased* the likelihood of treatment as

$$
\dd_t(a_t, h_t, \epsilon_t) = \begin{cases}
a_t &\text{ if } \epsilon_t < \delta \\
1 &\text{ otherwise.}
\end{cases}
$$Assume we want to increase the likelihood of initiating treatment by 2-fold. We can implement this in R with

```{webr-r}
delta <- 0.5
d_ipsi_up <- function(data, trt) {
  eps <- runif(nrow(data), 0, 1)
  ifelse(eps < delta, data[[trt]], 1)
}
```

## Problem 1

What if we wanted to *decrease* the likelihood of initiating treatment by 2-fold? Implement this shift function in R. As a reminder

$$
\dd_t(a_t, h_t, \epsilon_t) = \begin{cases}
a_t &\text{ if } \epsilon_t < \delta \\
0 &\text{ otherwise.}
\end{cases}
$$


```{webr-r}
delta <- 0.5
d_ipsi_down <- # Write your shift function here!
```

<details>

<summary style="color: grey; font-weight: 400;">

✅ Solution 

</summary>

```{r eval=FALSE}
delta <- 0.5
d_ipsi_down <- function(data, trt) {
  eps <- runif(nrow(data), 0, 1)
  ifelse(eps < delta, data[[trt]], 0)
}
```

</details>

::: {.callout-note appearance="simple"}
`lmtp` already implements `d_ipsi_up` and `d_ipsi_down` as a single shift function factory, `ipsi()`!

-   Risk ratio IPSIs that increase the likelihood of treatment should be specified with a value greater than 1 (i.e. a risk ratio IPSI that increases the likelihood of treatment 2-fold is equivalent to `ipsi(2)`).

-   IPSIs that decrease the likelihood of treatment should be specified with a value less than 1 (i.e. a risk ratio IPSI that decreases the likelihood of treatment 2-fold is equivalent to `ipsi(0.5)`)
:::

Let's apply the shift function that increases the likelihood of initiating treatment by 2-fold to `covid` dataset.

```{webr-r}
W <- c("age", "sex", "bmi", "smoke", "o2", 
       "num_comorbid", "num_symptoms", 
        "bilat", "dyspnea", "hyper")

lmtp_tmle(
  data = covid, 
  trt = "A", 
  outcome = "event", 
  baseline = W, 
  outcome_type = "binomial", 
  shift = ipsi(2), 
  folds = 1, 
  learners_trt = "SL.glm", 
  learners_outcome = "SL.glm"
)
```

------------------------------------------------------------------------

Estimating the effect of incremental propensity scores based on the risk ratio are easy to do with `lmtp`. Just use the `ipsi()` function as the input for the `shift` argument!
